name: Check
on: push
jobs:
    check:
        name: Check
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v2
              with: 
                ref: ${{ github.event.pull_request.head.sha }}
            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.8
            - name: Install Requirements
              run: |
                  python -m pip install --upgrade pip
                  pip install 'black==19.10b0'
            - name: Lint Check
              run: |
                  black . --check
            - name: Static Analysis
              uses: jpetrucciani/mypy-check@master
              with:
                path: 'app'
