name: Purpleair Sync

on:
    schedule:
      - cron: "0 2 * * *"

jobs:
    create_pr:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
            with:
              ref: purpleair_sync
          - name: Create PR
            uses: repo-sync/pull-request@v2
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                pr_title: "Purpleair Sync"
                pr_body: "Automated PR" 
                source_branch: "purpleair_sync"

